### Import Libraries

In [ ]:
import pandas as pd
import numpy as np

### Load Dataset

In [ ]:
df = pd.read_csv('/content/RTA Dataset.csv')

### Basic Dataset Overview

In [ ]:
print("Shape of dataset:", df.shape)
print("\nColumns:\n", df.columns.tolist())

Shape of dataset: (12316, 32)

Columns:
 ['Time', 'Day_of_week', 'Age_band_of_driver', 'Sex_of_driver', 'Educational_level', 'Vehicle_driver_relation', 'Driving_experience', 'Type_of_vehicle', 'Owner_of_vehicle', 'Service_year_of_vehicle', 'Defect_of_vehicle', 'Area_accident_occured', 'Lanes_or_Medians', 'Road_allignment', 'Types_of_Junction', 'Road_surface_type', 'Road_surface_conditions', 'Light_conditions', 'Weather_conditions', 'Type_of_collision', 'Number_of_vehicles_involved', 'Number_of_casualties', 'Vehicle_movement', 'Casualty_class', 'Sex_of_casualty', 'Age_band_of_casualty', 'Casualty_severity', 'Work_of_casuality', 'Fitness_of_casuality', 'Pedestrian_movement', 'Cause_of_accident', 'Accident_severity']

### Preview Data

In [ ]:
df.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury

In [ ]:
df.sample(10)

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
7123,13:00:00,Thursday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,Unknown,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,Overtaking,Slight Injury
4208,7:49:00,Thursday,18-30,Male,NaN,NaN,NaN,Lorry (41?100Q),Owner,1-2yr,...,Other,na,na,na,na,Self-employed,Normal,Not a Pedestrian,Overtaking,Serious Injury
617,18:13:00,Tuesday,31-50,Male,Junior high school,Employee,5-10yr,Turbo,Owner,2-5yrs,...,Turnover,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Serious Injury
4808,9:42:00,Friday,18-30,Male,Elementary school,Owner,Above 10yr,Pick up upto 10Q,NaN,NaN,...,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,No priority to pedestrian,Slight Injury
8970,17:44:00,Friday,Under 18,Male,NaN,NaN,NaN,Public (13?45 seats),Owner,2-5yrs,...,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the left,Slight Injury
80,18:48:00,Wednesday,31-50,Male,Junior high school,Employee,1-2yr,Lorry (11?40Q),Owner,Unknown,...,Going straight,Driver or rider,Female,31-50,3,Other,Normal,Not a Pedestrian,Changing lane to the left,Serious Injury
11874,17:10:00,Wednesday,18-30,Male,NaN,NaN,NaN,Automobile,Owner,Above 10yr,...,Going straight,Driver or rider,Male,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the left,Slight Injury
4941,14:04:00,Thursday,Under 18,Male,High school,Owner,Above 10yr,Automobile,Owner,Unknown,...,Going straight,Passenger,Male,18-30,3,Driver,Normal,Not a Pedestrian,Other,Slight Injury
615,18:56:00,Monday,Unknown,Female,Junior high school,Employee,2-5yr,Lorry (11?40Q),Owner,2-5yrs,...,Going straight,Driver or rider,Male,Over 51,3,NaN,NaN,Not a Pedestrian,Changing lane to the left,Slight Injury
5304,19:00:00,Sunday,31-50,Male,Junior high school,Employee,Below 1yr,Automobile,Owner,NaN,...,Moving Backward,Driver or rider,Male,Over 51,3,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury

### Dataset Information

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  object
 1   Day_of_week                  12316 non-null  object
 2   Age_band_of_driver           12316 non-null  object
 3   Sex_of_driver                12316 non-null  object
 4   Educational_level            11575 non-null  object
 5   Vehicle_driver_relation      11737 non-null  object
 6   Driving_experience           11487 non-null  object
 7   Type_of_vehicle              11366 non-null  object
 8   Owner_of_vehicle             11834 non-null  object
 9   Service_year_of_vehicle      8388 non-null   object
 10  Defect_of_vehicle            7889 non-null   object
 11  Area_accident_occured        12077 non-null  object
 12  Lanes_or_Medians             11931 non-null  object
 13  Road_allignment              12174 non-null  object
 14  Types_of_Junction            11429 non-null  object
 15  Road_surface_type            12144 non-null  object
 16  Road_surface_conditions      12316 non-null  object
 17  Light_conditions             12316 non-null  object
 18  Weather_conditions           12316 non-null  object
 19  Type_of_collision            12161 non-null  object
 20  Number_of_vehicles_involved  12316 non-null  int64
 21  Number_of_casualties         12316 non-null  int64
 22  Vehicle_movement             12008 non-null  object
 23  Casualty_class               12316 non-null  object
 24  Sex_of_casualty              12316 non-null  object
 25  Age_band_of_casualty         12316 non-null  object
 26  Casualty_severity            12316 non-null  object
 27  Work_of_casuality            9118 non-null   object
 28  Fitness_of_casuality         9681 non-null   object
 29  Pedestrian_movement          12316 non-null  object
 30  Cause_of_accident            12316 non-null  object
 31  Accident_severity            12316 non-null  object
dtypes: int64(2), object(30)
memory usage: 3.0+ MB

### Understand categorical values

In [ ]:
for col in df.select_dtypes(include='object'):
    print(col, df[col].nunique())

Time 1074
Day_of_week 7
Age_band_of_driver 5
Sex_of_driver 3
Educational_level 7
Vehicle_driver_relation 4
Driving_experience 7
Type_of_vehicle 17
Owner_of_vehicle 4
Service_year_of_vehicle 6
Defect_of_vehicle 3
Area_accident_occured 14
Lanes_or_Medians 7
Road_allignment 9
Types_of_Junction 8
Road_surface_type 5
Road_surface_conditions 4
Light_conditions 4
Weather_conditions 9
Type_of_collision 10
Vehicle_movement 13
Casualty_class 4
Sex_of_casualty 3
Age_band_of_casualty 6
Casualty_severity 4
Work_of_casuality 7
Fitness_of_casuality 5
Pedestrian_movement 9
Cause_of_accident 20
Accident_severity 3

### Check for Missing Values (only seeing)

In [ ]:
df.isnull().sum()

Time                              0
Day_of_week                       0
Age_band_of_driver                0
Sex_of_driver                     0
Educational_level               741
Vehicle_driver_relation         579
Driving_experience              829
Type_of_vehicle                 950
Owner_of_vehicle                482
Service_year_of_vehicle        3928
Defect_of_vehicle              4427
Area_accident_occured           239
Lanes_or_Medians                385
Road_allignment                 142
Types_of_Junction               887
Road_surface_type               172
Road_surface_conditions           0
Light_conditions                  0
Weather_conditions                0
Type_of_collision               155
Number_of_vehicles_involved       0
Number_of_casualties              0
Vehicle_movement                308
Casualty_class                    0
Sex_of_casualty                   0
Age_band_of_casualty              0
Casualty_severity                 0
Work_of_casuality              3198
Fitness_of_casuality           2635
Pedestrian_movement               0
Cause_of_accident                 0
Accident_severity                 0
dtype: int64

### Check for Duplicate Rows

In [ ]:
df.duplicated().sum()

np.int64(0)

### Basic Statistical Summary

In [ ]:
df.describe()

       Number_of_vehicles_involved  Number_of_casualties
count                 12316.000000          12316.000000
mean                      2.040679              1.548149
std                       0.688790              1.007179
min                       1.000000              1.000000
25%                       2.000000              1.000000
50%                       2.000000              1.000000
75%                       2.000000              2.000000
max                       7.000000              8.000000