## Load Dataset

In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv("RTA Dataset.csv")
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

Shape: (12316, 32)
Columns: ['Time', 'Day_of_week', 'Age_band_of_driver', 'Sex_of_driver', 'Educational_level', 'Vehicle_driver_relation', 'Driving_experience', 'Type_of_vehicle', 'Owner_of_vehicle', 'Service_year_of_vehicle', 'Defect_of_vehicle', 'Area_accident_occured', 'Lanes_or_Medians', 'Road_allignment', 'Types_of_Junction', 'Road_surface_type', 'Road_surface_conditions', 'Light_conditions', 'Weather_conditions', 'Type_of_collision', 'Number_of_vehicles_involved', 'Number_of_casualties', 'Vehicle_movement', 'Casualty_class', 'Sex_of_casualty', 'Age_band_of_casualty', 'Casualty_severity', 'Work_of_casuality', 'Fitness_of_casuality', 'Pedestrian_movement', 'Cause_of_accident', 'Accident_severity']

In [16]:
df.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,...,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,...,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,...,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury

## Select Relevant Columns
Keep only required columns for focused analysis

In [17]:
cols = [
    "Accident_severity",
    "Number_of_casualties",
    "Time",
    "Day_of_week",
    "Area_accident_occured",
    "Types_of_Junction",
    "Road_allignment",
    "Lanes_or_Medians",
    "Weather_conditions",
    "Light_conditions",
    "Road_surface_conditions",
    "Type_of_collision",
    "Vehicle_movement",
    "Cause_of_accident",
    "Age_band_of_driver",
    "Driving_experience",
    "Sex_of_driver",
    "Type_of_vehicle"
]

df = df[cols]

print("Shape after column selection:", df.shape)

Shape after column selection: (12316, 18)

## Standardize Missing Values

In [18]:
missing_values = ["Unknown", "unknown", "NA", "-", ""]

for value in missing_values:
    df = df.replace(value, np.nan)

df.isnull().sum()

Accident_severity             0
Number_of_casualties          0
Time                          0
Day_of_week                   0
Area_accident_occured       261
Types_of_Junction          1078
Road_allignment             142
Lanes_or_Medians            442
Weather_conditions          292
Light_conditions              0
Road_surface_conditions       0
Type_of_collision           169
Vehicle_movement            396
Cause_of_accident            25
Age_band_of_driver         1548
Driving_experience          862
Sex_of_driver               178
Type_of_vehicle             950
dtype: int64

## Check Unique Values (IMPORTANT BEFORE CLEANING)

In [19]:
for col in df.columns:
    print("\nColumn:", col)
    print("Unique Values:", df[col].nunique())
    print(df[col].unique())

Column: Accident_severity
Unique Values: 3
['Slight Injury' 'Serious Injury' 'Fatal injury']

Column: Number_of_casualties
Unique Values: 8
[2 1 3 4 6 5 8 7]

Column: Time
Unique Values: 1074
['17:02:00' '1:06:00' '14:15:00' ... '7:24:00' '19:18:00' '2:47:00']

Column: Day_of_week
Unique Values: 7
['Monday' 'Sunday' 'Friday' 'Wednesday' 'Saturday' 'Thursday' 'Tuesday']

Column: Area_accident_occured
Unique Values: 13
['Residential areas' 'Office areas' '  Recreational areas'
 ' Industrial areas' nan 'Other' ' Church areas' '  Market areas'
 'Rural village areas' ' Outside rural areas' ' Hospital areas'
 'School areas' 'Rural village areasOffice areas' 'Recreational areas']

Column: Types_of_Junction
Unique Values: 7
['No junction' 'Y Shape' 'Crossing' 'O Shape' 'Other' nan 'T Shape'
 'X Shape']

Column: Road_allignment
Unique Values: 9
['Tangent road with flat terrain' nan
 'Tangent road with mild grade and flat terrain' 'Escarpments'
 'Tangent road with rolling terrain' 'Gentle horizontal curve'
 'Tangent road with mountainous terrain and'
 'Steep grade downward with mountainous terrain' 'Sharp reverse curve'
 'Steep grade upward with mountainous terrain']

Column: Lanes_or_Medians
Unique Values: 6
[nan 'Undivided Two way' 'other' 'Double carriageway (median)' 'One way'
 'Two-way (divided with solid lines road marking)'
 'Two-way (divided with broken lines road marking)']

Column: Weather_conditions
Unique Values: 8
['Normal' 'Raining' 'Raining and Windy' 'Cloudy' 'Other' 'Windy' 'Snow'
 nan 'Fog or mist']

Column: Light_conditions
Unique Values: 4
['Daylight' 'Darkness - lights lit' 'Darkness - no lighting'
 'Darkness - lights unlit']

Column: Road_surface_conditions
Unique Values: 4
['Dry' 'Wet or damp' 'Snow' 'Flood over 3cm. deep']

Column: Type_of_collision
Unique Values: 9
['Collision with roadside-parked vehicles'
 'Vehicle with vehicle collision' 'Collision with roadside objects'
 'Collision with animals' 'Other' 'Rollover' 'Fall from vehicles'
 'Collision with pedestrians' 'With Train' nan]

Column: Vehicle_movement
Unique Values: 12
['Going straight' 'U-Turn' 'Moving Backward' 'Turnover' 'Waiting to go'
 'Getting off' 'Reversing' nan 'Parked' 'Stopping' 'Overtaking' 'Other'
 'Entering a junction']

Column: Cause_of_accident
Unique Values: 19
['Moving Backward' 'Overtaking' 'Changing lane to the left'
 'Changing lane to the right' 'Overloading' 'Other'
 'No priority to vehicle' 'No priority to pedestrian' 'No distancing'
 'Getting off the vehicle improperly' 'Improper parking' 'Overspeed'
 'Driving carelessly' 'Driving at high speed' 'Driving to the left' nan
 'Overturning' 'Turnover' 'Driving under the influence of drugs'
 'Drunk driving']

Column: Age_band_of_driver
Unique Values: 4
['18-30' '31-50' 'Under 18' 'Over 51' nan]

Column: Driving_experience
Unique Values: 6
['1-2yr' 'Above 10yr' '5-10yr' '2-5yr' nan 'No Licence' 'Below 1yr']

Column: Sex_of_driver
Unique Values: 2
['Male' 'Female' nan]

Column: Type_of_vehicle
Unique Values: 17
['Automobile' 'Public (> 45 seats)' 'Lorry (41?100Q)' nan
 'Public (13?45 seats)' 'Lorry (11?40Q)' 'Long lorry' 'Public (12 seats)'
 'Taxi' 'Pick up upto 10Q' 'Stationwagen' 'Ridden horse' 'Other' 'Bajaj'
 'Turbo' 'Motorcycle' 'Special vehicle' 'Bicycle']

## Fill Missing Values

In [20]:
for col in df.columns:
    if df[col].dtype == "object":
        mode_value = df[col].mode()[0]
        df[col] = df[col].fillna(mode_value)
    else:
        median_value = df[col].median()
        df[col] = df[col].fillna(median_value)

df.isnull().sum()

Accident_severity          0
Number_of_casualties       0
Time                       0
Day_of_week                0
Area_accident_occured      0
Types_of_Junction          0
Road_allignment            0
Lanes_or_Medians           0
Weather_conditions         0
Light_conditions           0
Road_surface_conditions    0
Type_of_collision          0
Vehicle_movement           0
Cause_of_accident          0
Age_band_of_driver         0
Driving_experience         0
Sex_of_driver              0
Type_of_vehicle            0
dtype: int64

## Clean Text Data

In [21]:
for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].str.strip()
        df[col] = df[col].str.lower()

## Convert Data Types

In [22]:
# Convert Number_of_casualties to numeric
df["Number_of_casualties"] = pd.to_numeric(df["Number_of_casualties"], errors="coerce")

# Convert Time to datetime
df["Time"] = pd.to_datetime(df["Time"], format="%H:%M:%S", errors="coerce")

In [23]:
df.isna().sum()

Accident_severity          0
Number_of_casualties       0
Time                       0
Day_of_week                0
Area_accident_occured      0
Types_of_Junction          0
Road_allignment            0
Lanes_or_Medians           0
Weather_conditions         0
Light_conditions           0
Road_surface_conditions    0
Type_of_collision          0
Vehicle_movement           0
Cause_of_accident          0
Age_band_of_driver         0
Driving_experience         0
Sex_of_driver              0
Type_of_vehicle            0
dtype: int64

## Remove Invalid Values

In [24]:
# Remove negative casualties if any
df = df[df["Number_of_casualties"] >= 0]
# len(df[df["Number_of_casualties"] < 0]) = 0

## Remove Duplicates

In [25]:
df = df.drop_duplicates()
df = df.reset_index(drop=True)

print("Final Shape:", df.shape)

Final Shape: (12315, 18)

In [26]:
df.head()

,Accident_severity,Number_of_casualties,Time,Day_of_week,Area_accident_occured,Types_of_Junction,Road_allignment,Lanes_or_Medians,Weather_conditions,Light_conditions,Road_surface_conditions,Type_of_collision,Vehicle_movement,Cause_of_accident,Age_band_of_driver,Driving_experience,Sex_of_driver,Type_of_vehicle
0,slight injury,2,1900-01-01 17:02:00,monday,residential areas,no junction,tangent road with flat terrain,two-way (divided with broken lines road marking),normal,daylight,dry,collision with roadside-parked vehicles,going straight,moving backward,18-30,1-2yr,male,automobile
1,slight injury,2,1900-01-01 17:02:00,monday,office areas,no junction,tangent road with flat terrain,undivided two way,normal,daylight,dry,vehicle with vehicle collision,going straight,overtaking,31-50,above 10yr,male,public (> 45 seats)
2,serious injury,2,1900-01-01 17:02:00,monday,recreational areas,no junction,tangent road with flat terrain,other,normal,daylight,dry,collision with roadside objects,going straight,changing lane to the left,18-30,1-2yr,male,lorry (41?100q)
3,slight injury,2,1900-01-01 01:06:00,sunday,office areas,y shape,tangent road with mild grade and flat terrain,other,normal,darkness - lights lit,dry,vehicle with vehicle collision,going straight,changing lane to the right,18-30,5-10yr,male,public (> 45 seats)
4,slight injury,2,1900-01-01 01:06:00,sunday,industrial areas,y shape,tangent road with flat terrain,other,normal,darkness - lights lit,dry,vehicle with vehicle collision,going straight,overtaking,18-30,2-5yr,male,automobile

## Verify Cleaned Data

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12315 entries, 0 to 12314
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Accident_severity        12315 non-null  object
 1   Number_of_casualties     12315 non-null  int64
 2   Time                     12315 non-null  datetime64[ns]
 3   Day_of_week              12315 non-null  object
 4   Area_accident_occured    12315 non-null  object
 5   Types_of_Junction        12315 non-null  object
 6   Road_allignment          12315 non-null  object
 7   Lanes_or_Medians         12315 non-null  object
 8   Weather_conditions       12315 non-null  object
 9   Light_conditions         12315 non-null  object
 10  Road_surface_conditions  12315 non-null  object
 11  Type_of_collision        12315 non-null  object
 12  Vehicle_movement         12315 non-null  object
 13  Cause_of_accident        12315 non-null  object
 14  Age_band_of_driver       12315 non-null  object
 15  Driving_experience       12315 non-null  object
 16  Sex_of_driver            12315 non-null  object
 17  Type_of_vehicle          12315 non-null  object
dtypes: datetime64[ns](1), int64(1), object(16)
memory usage: 1.7+ MB

# FEATURE ENGINEERING

## Extract Hour

In [29]:
df["Hour"] = df["Time"].dt.hour

## Create Time Period

In [30]:
def get_time_period(hour):
    if hour >= 0 and hour < 6:
        return "night"
    elif hour >= 6 and hour < 12:
        return "morning"
    elif hour >= 12 and hour < 18:
        return "afternoon"
    else:
        return "evening"

df["Time_period"] = df["Hour"].apply(get_time_period)

## Create Severity Score

In [31]:
severity_map = {
    "slight injury": 1,
    "serious injury": 2,
    "fatal injury": 3
}

df["severity_score"] = df["Accident_severity"].map(severity_map)

## Create Weekend Flag

In [32]:
df["is_weekend"] = df["Day_of_week"].isin(["saturday", "sunday"])

## Clean Area (Fix Messy Values)
"Rural village areasOffice areas" → bad data

In [37]:
print((df["Area_accident_occured"] == "rural village areasoffice areas").sum())

print("thats ~0.16% of data")

0
thats ~0.16% of data

In [35]:
df = df[df["Area_accident_occured"] != "rural village areasoffice areas"]

In [38]:
df.shape

(12295, 22)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12295 entries, 0 to 12314
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Accident_severity        12295 non-null  object
 1   Number_of_casualties     12295 non-null  int64
 2   Time                     12295 non-null  datetime64[ns]
 3   Day_of_week              12295 non-null  object
 4   Area_accident_occured    12295 non-null  object
 5   Types_of_Junction        12295 non-null  object
 6   Road_allignment          12295 non-null  object
 7   Lanes_or_Medians         12295 non-null  object
 8   Weather_conditions       12295 non-null  object
 9   Light_conditions         12295 non-null  object
 10  Road_surface_conditions  12295 non-null  object
 11  Type_of_collision        12295 non-null  object
 12  Vehicle_movement         12295 non-null  object
 13  Cause_of_accident        12295 non-null  object
 14  Age_band_of_driver       12295 non-null  object
 15  Driving_experience       12295 non-null  object
 16  Sex_of_driver            12295 non-null  object
 17  Type_of_vehicle          12295 non-null  object
 18  Hour                     12295 non-null  int32
 19  Time_period              12295 non-null  object
 20  severity_score           12295 non-null  int64
 21  is_weekend               12295 non-null  bool
dtypes: bool(1), datetime64[ns](1), int32(1), int64(2), object(17)
memory usage: 2.0+ MB